---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 31.01.2022 22:53
---
InBattle = false
idList = {
    FourCC("n000"),
    FourCC("n001"),
    FourCC("n002"),
    FourCC("n003"),
    FourCC("n004"),
}
function StartBattle(rectActivator)
    InBattle = true
    --print("Start")
    local x, y = GetRectCenterX(rectActivator), GetRectCenterY(rectActivator)
    local interval = 1
    local countEnemy = 10
    EnemySpawn(idList, interval, countEnemy, "randomSides", x, y,1)
end

function EnemySpawn(id, interval, countEnemy, spawnType, xs, ys,number)
    local k = 0
    local tempEnemy = {}
    TimerStart(CreateTimer(), interval, true, function()
        k = k + 1
        if k > countEnemy then
            if TableChkAlive(tempEnemy, countEnemy,xs,ys) then
                DestroyTimer(GetExpiredTimer())

                if number>=#id then
                    ResetCameraToNormal(xs, ys)
                else
                    EnemySpawn(id, interval, countEnemy, "randomSides", xs, ys,number+1)
                end

            end
        else
            local seed = { -1, 1 }
            local x = xs - 800 * seed[GetRandomInt(1, 2)]
            local y = ys - GetRandomInt(-500, 500)
            local new = CreateUnit(Player(10), id[number], x, y, 0)
            AIMoveOnSpawn(new, xs, ys,3)
            table.insert(tempEnemy, new)
        end
    end)
end

function TableChkAlive(table, max,xs,ys)
    local k = 0

    for i = 1, #table do
        if not UnitAlive(table[i]) then
            k = k + 1
        else
            local x,y=GetUnitXY(table[i])
            if PointContentDestructable(x,y,250) then
                AIMoveOnSpawn(table[i], xs, ys,3)
                --print("надо пройти на сквозь")
            end
        end
    end
    if k >= max then
        --print("все мерты, конец волны")
        return true
    else
        --print("юнитов " .. k .. " " .. max)
        return false
    end
end

function ResetCameraToNormal(x, y)
    SetCameraBoundsToRect(bj_mapInitialPlayableArea)
    normal_sound("Sound\\Interface\\LeftGlueScreenPopUp", x, y)
    --
    BlzFrameSetVisible(AllChain, false)
    for i = 1, #BlockCameraDestructable do
        RemoveDestructable(BlockCameraDestructable[i])
    end
end

function AIMoveOnSpawn(unit, x, y,period)
    SetUnitPathing(unit, false)
    IssuePointOrder(unit, "attack", x, y)
    TimerStart(CreateTimer(), period, false, function()
        SetUnitPathing(unit, true)
    end)
end