---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 19.02.2023 19:59
---
function StartFireCircle(data)
    AddSpecialEffectTarget("Effect/flame aura3.mdl",HeroMegumin,"origin")
    TimerStart(CreateTimer(), 0.1, true, function()
        local _,enemy=UnitDamageArea(HeroMegumin, data.FireCircleDamage, GetUnitX(HeroMegumin), GetUnitY(HeroMegumin), 150)
        if enemy then
            DestroyEffect(AddSpecialEffect("Abilities\\Weapons\\AncestralGuardianMissile\\AncestralGuardianMissile.mdl",GetUnitXY(enemy)))
        end
    end)
end