---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 25.02.2023 13:55
---
function StartFindBones(data)
    local x, y = GetUnitXY(HeroMegumin)
    TimerStart(CreateTimer(), 0.5, true, function()
        local e = nil
        local k = 0
        --print("ищем")
        x, y = GetUnitXY(HeroMegumin)
        GroupEnumUnitsInRange(perebor, x, y, 250, nil)
        while true do
            e = FirstOfGroup(perebor)

            if e == nil then
                break
            end
            if not UnitAlive(e) and not IsUnitType(e, UNIT_TYPE_HERO) then
                --print("найден труп", GetUnitName(e))
                DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Undead\\RaiseSkeletonWarrior\\RaiseSkeleton.mdl", GetUnitXY(e)))
                UnitAddMana(HeroMegumin, data.FindBonesAmount)
                RemoveUnit(e)
            end
            GroupRemoveUnit(perebor, e)
        end

    end)
end