---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 19.02.2023 15:40
---
function StartManaReplenish(hero,data)
    TimerStart(CreateTimer(), 1, true, function()
        UnitAddMana(hero,data.ManaReplenishCount)
    end)
end