---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 19.02.2023 20:44
---
function StartMeteor(data)
    --Effect/FlameGroundEX.mdl
    TimerStart(CreateTimer(), 1.5, true, function()
        local enemy=FindFirstEnemy(HeroMegumin,1000)
        local x,y=GetUnitXY(enemy)
        if enemy then
            MarkAndFall(x, y, "Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile", HeroMegumin,0.5)
        end
    end)
end

function MarkAndFall(x, y, effModel, hero,delay)
    local mark = AddSpecialEffect("Snipe Target", x, y)
    local data=GetUnitData(hero)
    BlzSetSpecialEffectScale(mark, 5)
    if not delay then
        delay=2
    end
    local deep=50
    if effModel=="Icicle" then
        deep=GetRandomInt(200, 400)
    end
    TimerStart(CreateTimer(), delay, false, function()

        local FallenEff = AddSpecialEffect(effModel, x, y)
        BlzSetSpecialEffectZ(FallenEff, GetTerrainZ(x,y)+1000)
        BlzSetSpecialEffectYaw(FallenEff, math.rad(GetRandomReal(0, 360)))
        BlzSetSpecialEffectScale(FallenEff, 5)
        TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
            local z = BlzGetLocalSpecialEffectZ(FallenEff)
            BlzSetSpecialEffectZ(FallenEff, z - 50)
            if z + deep <= GetTerrainZ(x, y) then
                DestroyEffect(mark)
                BlzSetSpecialEffectPosition(mark, 5000, 5000, 0)
                DestroyTimer(GetExpiredTimer())

                local nd =nil
                --SetDestructableInvulnerable(nd,true)
                DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", x, y))
                --PlayerSeeNoiseInRangeTimed(0.5, x, y)
                UnitDamageArea(hero, data.FirstMeteorDamage, x, y, 150) --при падении камня
                local k = GetUnitLifePercent(hero) / 100
                k = 1 - k
                if effModel =="Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile" then
                    DestroyEffect(FallenEff)
                    DestroyEffect(AddSpecialEffect("Effect/FlameGroundEX.mdl", x, y))
                else
                    nd= CreateDestructableZ(FourCC('B002'), x, y, 0, 0, 5, 1)
                end
                TimerStart(CreateTimer(), 5 + (k * 5), false, function()
                    DestroyEffect(FallenEff)
                    BlzSetSpecialEffectPosition(FallenEff, 999, 999, 999)
                    KillDestructable(nd)
                end)
            end
        end)
    end)
end