---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 19.02.2023 14:28
---
function StartAiPhoenix(data)
    local fen = CreateUnit(GetOwningPlayer(data.UnitHero), FourCC("hphx"), data.x, data.y, 0)
    StartCompanionAI(fen, data)

end