---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 12:16
---
function InitTalonBDForAqua()
    AquaTalon = {
        [1] = {
            name = "Пивной уворот",
            icon = "DDSICO\\BearEvasion",
            description = "Аква бежит непонятно как и имеет шанс DS%% уклонится от атаки",
            level = 0,
            DS = { 10, 20, 30 },
            pos = 1,
        },
        [2] = {
            name = "Струя воды",
            icon = "DDSICO\\ColdBolt",
            description = "Автоматически наносит DS урона ледяным болтом раз в секунду",
            level = 0,
            DS = { 100, 200, 300 },
            pos = 2,
        },
        [3] = {
            name = "Повод для акулы",
            icon = "DDSICO\\SharkStrike",
            description = "Каждый DS теперь теперь призывает акулу, мгновенно убивающую случайных врагов",
            level = 0,
            DS = { "брызг воды" },
            pos = 3,
        },
        [4] = {
            name = "Посох маны",
            icon = "DDSICO\\ManaStaff",
            description = "Увеличивает максимальную ману ещё на DS пунктов",
            level = 0,
            DS = { 200, 200, 200 },
            pos = 4,
        },

    }
end