---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 17.02.2023 22:14
---
function InitRegistryEvent(hero)
    local enterTrig = CreateTrigger()
    TriggerRegisterUnitInRange(enterTrig, hero, 200, nil)
    TriggerAddAction(enterTrig, function()
        if not IsUnitHidden(hero) then
            local entering=GetTriggerUnit()


            if GetUnitTypeId(entering) == FourCC("e000") then
                --print(GetUnitName(entering))

                EffectFromUnit2Unit(nil,"Firebrand Shot Yellow", hero, entering,"add exp")
                KillUnit(entering)
            end
        end
    end)

end

