---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 0:32
---
function InitTalonBDForDarkNess()
    CreateOSKEY_1Actions()
    CreateOSKEY_2Actions()
    CreateOSKEY_3Actions()
    DarknessTalon = {
        [1] = {
            name = "Кровавый меч",
            icon = "DDSICO\\BloodAndBlade",
            description = "Убийства врагов исцеляют на DS ",
            level = 0,
            DS = { 1, 2, 3 },
        },
        [2] = {
            name = "Маска льва",
            icon = "DDSICO\\LionMask",
            description = "При получении 300 урона выпускает волну силы наносящую DS урон",
            level = 0,
            DS = { 100, 200, 300 },
        },
        [3] = {
            name = "Разбитое сердце",
            icon = "DDSICO\\BrokenHeart",
            description = "Получение урона возвращается DS%% урона всем врагам в малом радиусе 250",
            level = 0,
            DS = { 100, 200, 300 },
        }
    }
end

DialogTalonActive=false
function CreateDialogTalon(hero)
    DialogTalonActive=true
    if hero == HeroDarkness then

    end
    if not DialogMainWindow then
        DialogMainWindow = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
        TalonInSlot={}
        --print("11111111111111")
    end
    BlzFrameSetVisible(DialogMainWindow,true)
    local x, y = 0.2, 0.3
    for i = 1, 3 do
        local name, icon, text = CreateInfoTalonSingle(DialogMainWindow, x + (i - 1) * 0.2, y, i)
        SetTalonDescription(DarknessTalon,i, name, icon, text)

    end


end

function SetTalonDescription(BD, number, name, icon, text)
    BlzFrameSetText(name, BD[number].name)
    BlzFrameSetTexture(icon, BD[number].icon, 0, true)
    BlzFrameSetText(text, BD[number].description)
    TalonInSlot[number]=BD[number].name
end

function CreateInfoTalonSingle(BoxBarParent, x, y, i)
    local rama = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BoxBarParent, '', 0)
    BlzFrameSetTexture(rama, "Textures\\Black32", 0, true) --HPElement
    BlzFrameSetSize(rama, 0.15, 0.22)
    BlzFrameSetAbsPoint(rama, FRAMEPOINT_CENTER, x, y)

    local icon = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', rama, '', 0)
    BlzFrameSetTexture(icon, "DDSICO\\BrokenHeart", 0, true) --HPElement
    BlzFrameSetSize(icon, 0.08, 0.08)
    BlzFrameSetPoint(icon, FRAMEPOINT_TOP, rama, FRAMEPOINT_TOP, 0, 0)

    local name = BlzCreateFrameByType("TEXT", "ButtonChargesText", rama, "", 0)
    BlzFrameSetPoint(name, FRAMEPOINT_CENTER, rama, FRAMEPOINT_CENTER, 0.0, -0.02)
    BlzFrameSetText(name, "Название")

    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", rama, "StandardFrameTemplate", 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    BlzFrameSetPoint(tooltip, FRAMEPOINT_CENTER, rama, FRAMEPOINT_CENTER, 0, -0.05)
    BlzFrameSetSize(tooltip, 0.17, 0.125)
    BlzFrameSetSize(text, 0.17, 0.06)
    BlzFrameSetText(text, "Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?")
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, tooltip, FRAMEPOINT_LEFT, 0.02, -0.003)
    BlzFrameSetScale(text, 0.8)

    local press = BlzCreateFrameByType("TEXT", "ButtonChargesText", rama, "", 0)
    BlzFrameSetPoint(press, FRAMEPOINT_CENTER, rama, FRAMEPOINT_CENTER, 0.0, -0.05)
    BlzFrameSetText(press, "Нажмите " .. i)
    BlzFrameSetScale(press, 2)
    return name, icon, text
end

