---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 12:16
---
function InitTalonBDForKazuma()
    KazumaTalon = {
        [1] = {
            name = "Крепкая хватка",
            icon = "DDSICO\\StrongWeapon",
            description = "Увеличивает силу атаки меча на DS",
            level = 0,
            DS = { 50, 100, 150,200 },
            pos = 1,
        },
        [2] = {
            name = "Ледяной болт",
            icon = "DDSICO\\ColdBolt",
            description = "Автоматически наносит DS урона ледяным болтом",
            level = 0,
            DS = { 100, 200, 300 },
            pos = 2,
        },
        [3] = {
            name = "Удар акулы",
            icon = "DDSICO\\SharkStrike",
            description = "Раз в DS сек. появляется акула и полностью пожирает вражеского юнита",
            level = 0,
            DS = { 20, 15, 10 },
            pos = 3,
        },
        [4] = {
            name = "Рунный генератор",
            icon = "DDSICO\\RuneGenerator",
            description = "Из врагов начинают выпадать руны, восстанавливающие DS маны",
            level = 0,
            DS = { 10, 20, 30 },
            pos = 4,
        },
        [5] = {
            name = "Исцеляющий шаг",
            icon = "DDSICO\\HealStep",
            description = "Когда Казума двигается он немного исцеляется на DS здоровья, за каждые 2000 ед пути",
            level = 0,
            DS = { 50, 100, 150 },
            pos = 5,
        },
    }
end