---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 2:37
---
function LearnTalonByName(name)
    local data=HERO[0]
    if name=="Кровавый меч" then
        data.HasBloodBlade=true
    elseif name=="Маска льва" then
        data.LionMask=true
    elseif name=="Разбитое сердце" then
        data.BrokenHeart=true
    end
end
