---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 12:16
---
function InitTalonBDForMegumin()
    MeguminTalon = {
        [1] = {
            name = "Призыв петуеникса",
            icon = "DDSICO\\Phoeniks",
            description = "Призывает DS бессмертного феникса, точь в точь как у Келя",
            level = 0,
            DS = { "одного", "второго", "третьего" },
        },
        [2] = {
            name = "Пополняемый запас",
            icon = "DDSICO\\Manaregen",
            description = "Восстанавливает DS маны каждую секунду",
            level = 0,
            DS = { 1,2,3,4,5,6,7,8,9 },
        },
        [3] = {
            name = "Посох алых Мазоку",
            icon = "DDSICO\\ManaStaff",
            description = "Увеличивает максимальную ману ещё на DS пунктов",
            level = 0,
            DS = { 300, 300, 300, 300, 300, 300, 300, 300, 300, 300 },
        },
        [4] = {
            name = "Кольцо огня",
            icon = "DDSICO\\FireCircle",
            description = "Покрывает героя кольцом, которое наносит DS урона вокруг героя каждые 0.1 сек",
            level = 0,
            DS = { 20,40,60,80,100 },
        },
        [5] = {
            name = "Первый среди метеоров",
            icon = "DDSICO\\FirstMeteot",
            description = "Каждые 1.5 секунды на случайного врага падает метеор, наносящий DS урона по небольшой области",
            level = 0,
            DS = { 200,400,600,800,1000 },
        },

    }
end