---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 13:25
---
function EndJump(data)
    local hero=data.UnitHero
    local x,y=GetUnitXY(hero)
    DestroyEffect(AddSpecialEffect("ThunderclapCasterClassic", x,y))
    local _,_,_,t=UnitDamageArea(data.UnitHero, 300, x, y, 250)
    for i=1,#t do
        local angle=AngleBetweenUnits(hero,t[i])
        UnitAddForceSimple(t[i], angle, 20, 300)
    end
end