---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 25.02.2023 3:14
---
function HealStep(data)
    if data.HealStepAmount then
        if data.UnitHero == HeroKazuma then
            data.HealStepCurrent = data.HealStepCurrent + data.HeroMoveSpeed
            --print(data.HealStepCurrent)
            if data.HealStepCurrent > 2000 then
                data.HealStepCurrent = 0
                HealUnit(data.UnitHero, data.HealStepAmount)
            end
        end
    end
end