---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 13:54
---
function SpellSteal(data)
    if not data.StealOnCD then
        local x,y=GetUnitXY(data.UnitHero)
        x,y=MoveXY(x,y,300,GetUnitFacing(data.UnitHero))
        SetUnitAnimationByIndex(data.UnitHero,10)
        TimerStart(CreateTimer(), 1, false, function()

            local _, _, _, units = UnitDamageArea(data.UnitHero, 1, x, y, 250)
            for i = 1, #units do
                EffectFromUnit2Unit(nil,"Firebrand Shot Yellow", data.UnitHero, units[i],"add exp")
                FlyTextTagShadowStrike(units[i],"Успешная Кража",GetOwningPlayer(data.UnitHero))
            end
        end)
        data.StealOnCD=true
        TimerStart(CreateTimer(), 5, false, function()
            data.StealOnCD=false
        end)
    end
end