---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 14:17
---
function UltraGreed(data)
    if not data.UltraGreedOnCD then
        local find,_,units = FindUnitOfType(FourCC("e000"))
        if find then
            FlyTextTagShadowStrike(data.UnitHero,"Ультра жадность",GetOwningPlayer(data.UnitHero))
            data.UltraGreedOnCD=true

            for i=1,#units do
                EffectFromUnit2Unit(nil,"Firebrand Shot Yellow", data.UnitHero, units[i],"add exp")
                KillUnit(units[i])
            end
            TimerStart(CreateTimer(), 10, false, function()
                data.UltraGreedOnCD=false
            end)
        end
    end
end