---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 17.02.2023 20:59
---
function GetRandomSpawnXY(r)
    if not r then
        r = GetRandomInt(1, #RXY)
    end
    return RXY[r].x, RXY[r].y
end
RXY = {}
function InitEnterPoints()
    local _, _, t = FindUnitOfType(FourCC("h004"))
    for i = 1, #t do
        --print(i)
        ShowUnit(t[i], false)
        UnitAddAbility(t[i], FourCC("Aloc"))
        RXY[i]={}
        RXY[i].x, RXY[i].y = GetUnitXY(t[i])
        --print(GetRandomSpawnXY(i))
    end
end

CurrentWave=1
function StartSpawnMachine()
    local t = {
        FourCC("n005"),
    }
    TimerStart(CreateTimer(), 2, true, function()
        local x,y=GetRandomSpawnXY()
        local new=CreateUnit(Player(10), t[CurrentWave], x, y, 0)
        IssueTargetOrder(new,"attack",GetRandomEnemy())
    end)
end
function GetRandomEnemy()
    return HERO[0].UnitHero
end