---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 17.02.2023 20:59
---
function GetRandomSpawnXY(r)
    if not r then
        r = GetRandomInt(1, #RXY)
    end
    return RXY[r].x, RXY[r].y
end
RXY = {}
function InitEnterPoints()
    local _, _, t = FindUnitOfType(FourCC("h004"))
    for i = 1, #t do
        --print(i)
        ShowUnit(t[i], false)
        UnitAddAbility(t[i], FourCC("Aloc"))
        RXY[i]={}
        RXY[i].x, RXY[i].y = GetUnitXY(t[i])
        --print(GetRandomSpawnXY(i))
    end
end

CurrentWave=1
MaxCreep=40
CurrentCreepCount=0
function StartSpawnMachine()
    local t = {
        FourCC("n005"),
        FourCC("n006"),
        FourCC("n007"),
        FourCC("n000"),
        FourCC("n001"),
        FourCC("n002"),
        FourCC("n003"),
        FourCC("n004"),
    }
    local period=1.5
    local timeNextWave=30
    TimerStart(CreateTimer(), period, true, function()
        if CurrentCreepCount<=MaxCreep then
            local x,y=GetRandomSpawnXY()
            local new=CreateUnit(Player(10), t[CurrentWave], x, y, 0)
            IssueTargetOrder(new,"attack",GetRandomEnemy())
            CurrentCreepCount=CurrentCreepCount+1
            timeNextWave=timeNextWave-period
            if timeNextWave<=0 then
                if CurrentWave<#t then
                    CurrentWave=CurrentWave+1
                    timeNextWave=30
                end

            end
        else
            --print("слишком много крипов")
        end
    end)
end
function GetRandomEnemy()
    return HERO[0].UnitHero
end