---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 17.02.2023 20:59
---
function GetRandomSpawnXY(r)
    if not r then
        r = GetRandomInt(1, #RXY)
    end
    return RXY[r].x, RXY[r].y
end
RXY = {}
function InitEnterPoints()
    local _, _, t = FindUnitOfType(FourCC("h004"))
    for i = 1, #t do
        --print(i)
        ShowUnit(t[i], false)
        UnitAddAbility(t[i], FourCC("Aloc"))
        RXY[i]={}
        RXY[i].x, RXY[i].y = GetUnitXY(t[i])
        --print(GetRandomSpawnXY(i))
    end
end

CurrentWave=1
MaxCreep=40
CurrentCreepCount=0
function StartSpawnMachine()
    local t = {
        FourCC("n005"),
        FourCC("n006"),
        FourCC("n007"),
        FourCC("n000"),
        FourCC("n001"),
        FourCC("n002"),
        FourCC("n003"),
        FourCC("n004"),
        FourCC("nbdm"),
        FourCC("nbda"),
        FourCC("nbdw"),
        FourCC("nbds"),
        FourCC("nbdo"),

        FourCC("ncer"),
        FourCC("ncea"),
        FourCC("ncen"),
        FourCC("ncim"),
        FourCC("ncks"),
        FourCC("ncnk"),

        FourCC("nfor"),
        FourCC("nfot"),
        FourCC("nfod"),
        FourCC("ners"),
        FourCC("nerd"),
        FourCC("nerw"),

        FourCC("ntrv"),
        FourCC("nrvf"),
        FourCC("nrvs"),
        FourCC("nsrv"),
        FourCC("nrvl"),
        FourCC("ndrv"),
        FourCC("nrvi"),
        FourCC("nrvd"),

        FourCC("nogr"),
        FourCC("nogm"),
        FourCC("nomg"),
        FourCC("nowb"),
        FourCC("nowe"),
        FourCC("nowk"),
        FourCC("nplb"),
        FourCC("nplg"),

        FourCC("nrzs"),
        FourCC("nrzt"),
        FourCC("nrzb"),
        FourCC("nqbh"),
        FourCC("nrzm"),
        FourCC("nrzg"),

        FourCC("nslh"),
        FourCC("nslr"),
        FourCC("nslv"),
        FourCC("nsll"),



    }
    local period=1.5
    local timeNextWave=30
    TimerStart(CreateTimer(), period, true, function()
        if CurrentCreepCount<=MaxCreep then
            local x,y=GetRandomSpawnXY()
            local new=CreateUnit(Player(10), t[CurrentWave], x, y, 0)
            AddMaxLife(new, 50*CurrentWave)
            SetUnitAcquireRange(new,5000)
            BlzSetUnitRealField( new, UNIT_RF_SIGHT_RADIUS, 5000 )
            BlzSetUnitBaseDamage(new,BlzGetUnitBaseDamage(new,0)+CurrentWave,0)
            IssueTargetOrder(new,"attack",GetRandomEnemy())

            CurrentCreepCount=CurrentCreepCount+1
            timeNextWave=timeNextWave-period
            if timeNextWave<=0 then
                if CurrentWave<#t then
                    CurrentWave=CurrentWave+1
                    timeNextWave=30
                end

            end
        else
            --print("слишком много крипов")
        end
    end)
end
function GetRandomEnemy()
    return HERO[0].UnitHero
end