---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 19.02.2023 12:26
---
function HalfPartyHeal(data)
    TimerStart(CreateTimer(), 1, true, function()
        if data.UnitHero==HeroDarkness then
            local hp=GetUnitLifePercent(HeroDarkness)
            if hp<=50 then
                local heroes={
                    HeroKazuma,
                    HeroAqua,
                    HeroMegumin,
                }
                for i=1,#heroes do
                    local hph=GetUnitLifePercent(heroes[i])
                    if hph<50 then
                        HealUnit(heroes[i],data.HalfPartyHealAmount)
                    end
                end
            end
        end
    end)
end