---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 22:30
---
function LionMaskBlast(data)
    for i=1,12 do
        local angle=30*i
        CreateAndForceBullet(data.UnitHero, angle, 30, "Abilities\\Spells\\Orc\\Shockwave\\ShockwaveMissile", nil, nil, data.LionMaskDamage, 500)
    end
end