---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 15:34
---
function ReversePolarity(data)
    local hero=data.UnitHero
    local x,y=GetUnitXY(hero)
    DestroyEffect(AddSpecialEffect("Effect\\Concecration", x,y))
    StatCDText(5,data.DarkQ)
    local _,_,_,t=UnitDamageArea(data.UnitHero, 300, x, y, 300)
    for i=1,#t do
        local angle=AngleBetweenUnits(t[i],hero)
        local dist=DistanceBetweenXY(GetUnitX(hero),GetUnitY(hero),GetUnitXY(t[i]))
        UnitAddForceSimple(t[i], angle, 20, dist)
        IssueTargetOrder(t[i],"attack",hero)
    end
end