---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 16:21
---
function ReverseDamage(data)
    --Effect/PsychicTarget.mdl
    if not data.ReverseDamageOnCD then
        data.ReverseDamageOnCD = true
        data.ReverseDamage=true
        local eff = AddSpecialEffectTarget("Effect\\PsychicTarget.mdl", data.UnitHero, "chest")

        TimerStart(CreateTimer(), 5, false, function()
            DestroyEffect(eff)
            data.ReverseDamage=false
        end)
        TimerStart(CreateTimer(), 20, false, function()
            data.ReverseDamageOnCD = false
        end)

    end
end