---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.12.2021 17:52
---
function InitMouseClickEvent()
    --- LMB
    local TrigPressLMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigPressLMB, Player(i), EVENT_PLAYER_MOUSE_DOWN)
    end
    TriggerAddAction(TrigPressLMB, function()
        EnableUserControl(true)
        TimerStart(CreateTimer(), TIMER_PERIOD, false, function()
           -- EnableUserControl(true)
        end)
        TimerStart(CreateTimer(), 0.1, false, function()
            --EnableUserControl(true)
        end)
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then
           -- print("клик левой")

            --EnableUserControl(true)
            BlzPauseUnitEx(GetTriggerUnit(), true)
            IssueImmediateOrder(GetTriggerUnit(), "stop")
            BlzPauseUnitEx(GetTriggerUnit(), false)

            local data = HERO[GetPlayerId(GetTriggerPlayer())]
            data.LMBIsPressed = true

        end
    end)

    local TrigDEPressLMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigDEPressLMB, Player(i), EVENT_PLAYER_MOUSE_UP)
    end
    TriggerAddAction(TrigDEPressLMB, function()

        --EnableUserControl(true)
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_LEFT then


            --ForceUICancelBJ(Player(0))
            local data = HERO[GetPlayerId(GetTriggerPlayer())]
            data.LMBIsPressed = false
            local pid = data.pid

            GetPlayerMouseX[pid] = BlzGetTriggerPlayerMouseX()
            GetPlayerMouseY[pid] = BlzGetTriggerPlayerMouseY()

            if BlzGetTriggerPlayerMouseX() >= 0 and BlzGetTriggerPlayerMouseX() <= 0 then
                GetPlayerMouseX[pid], GetPlayerMouseY[pid] = MoveXY(GetUnitX(data.UnitHero), GetUnitY(data.UnitHero), 500, GetUnitFacing(data.UnitHero))
            end
            if UnitAlive(data.UnitHero) then

                if not data.SpaceForce then
                    if GetUnitTypeId(data.UnitHero) == KazumaID or GetUnitTypeId(data.UnitHero) == DarknessID then
                        AttackMelee(data)

                    end

                end

            end


        end
    end)
    ---------------------- RMB
    local TrigPressRMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigPressRMB, Player(i), EVENT_PLAYER_MOUSE_DOWN)
    end
    TriggerAddAction(TrigPressRMB, function()
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
            --print("клик правой")
            local data = HERO[GetPlayerId(GetTriggerPlayer())]
            data.RMBIsPressed = true
            local id = GetPlayerId(GetTriggerPlayer())
            if not GetUnitTypeId(data.UnitHero) == KazumaID then
                GetPlayerMouseX[id] = BlzGetTriggerPlayerMouseX()
                GetPlayerMouseY[id] = BlzGetTriggerPlayerMouseY()
            else
                data.StartWaveCastX = BlzGetTriggerPlayerMouseX()
                data.StartWaveCastY = BlzGetTriggerPlayerMouseY()
            end
            if data.UnitHero == HeroDarkness then
                PushHandWave(data, BlzGetTriggerPlayerMouseX(), BlzGetTriggerPlayerMouseY())

            end
        end
    end)

    local TrigDEPressRMB = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        TriggerRegisterPlayerEvent(TrigDEPressRMB, Player(i), EVENT_PLAYER_MOUSE_UP)
    end
    TriggerAddAction(TrigDEPressRMB, function()
        if BlzGetTriggerPlayerMouseButton() == MOUSE_BUTTON_TYPE_RIGHT then
            local data = HERO[GetPlayerId(GetTriggerPlayer())]
            data.RMBIsPressed = false
            local id = GetPlayerId(GetTriggerPlayer())
            if GetUnitTypeId(data.UnitHero) ~= KazumaID then
                GetPlayerMouseX[id] = BlzGetTriggerPlayerMouseX()
                GetPlayerMouseY[id] = BlzGetTriggerPlayerMouseY()
            else
                data.EndWaveCastX = BlzGetTriggerPlayerMouseX()
                data.EndWaveCastY = BlzGetTriggerPlayerMouseY()
                if GetUnitState(data.UnitHero, UNIT_STATE_MANA) > 10 and UnitAlive(data.UnitHero) then
                    SpellCastByName(data, "wave")
                    UnitAddMana(data.UnitHero, -10)
                else
                    print("недостаточно маны")
                end
            end


            --ClearPoints(data)
        end
    end)
end

