---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 19.02.2023 11:41
---
function AquaResRandomHero(data)
    if not data.ResOnCD then
        local cd=60
        local resHero=GetRandomDeadHero()
        if resHero then
            ReviveKonosubaHero(resHero)
            StatCDText(cd,data.AquaR)
            DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\ReviveHuman\\ReviveHuman.mdl",GetUnitXY(data.UnitHero)))
            data.ResOnCD = true
            TimerStart(CreateTimer(), cd, false, function()
                data.ResOnCD = false
            end)
        else
            print("все герои живы")
        end
    end
end

function GetRandomDeadHero()
    local heroes={
        HeroKazuma,
        HeroAqua,
        HeroDarkness,
        HeroMegumin,
    }
    local tmp={}
    for i=1,#heroes do
        if not UnitAlive(heroes[i]) then
            table.insert(tmp,heroes[i])
        end
    end
    local r=GetRandomInt(1,#tmp)
    return tmp[r]
end

function ReviveKonosubaHero(hero)
    local data=GetUnitData(hero)
    local x,y=5000, 5000
    if data.UnitHero==hero then
        x,y=GetUnitXY(hero)
    end
    ReviveHero(hero, x,y, true)
    SetUnitInvulnerable(hero, true)
    TimerStart(CreateTimer(), 2, false, function()
        SetUnitInvulnerable(hero, false)
        DestroyTimer(GetExpiredTimer())
    end)
    BlzFrameSetVisible(CrossFH[GetHandleId(hero)],false)
end