---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 18:20
---
function PartyHeal(data)
    if GetUnitState(data.UnitHero, UNIT_STATE_MANA)>30 then
        UnitAddMana(data.UnitHero,-30)
        local heroes={
            HeroKazuma,
            HeroAqua,
            HeroDarkness,
            HeroMegumin,
        }
        for i=1,#heroes do
            HealUnit(heroes[i],20)
            if not IsUnitHidden(heroes[i]) then
                DestroyEffect(AddSpecialEffect("Effect/AquaSpikeVersion2",GetUnitXY(heroes[i])))
                if data.HasSharkFromDeep then
                    FishEat(data,FindFirstEnemy(heroes[i],150))
                end
            end
            local times=3
            TimerStart(CreateTimer(), 1, true, function()
                times=times-1
                --print(GetUnitName(heroes[i]))
                HealUnit(heroes[i],20)
                if not IsUnitHidden(heroes[i]) then
                    DestroyEffect(AddSpecialEffect("Effect/AquaSpikeVersion2",GetUnitXY(heroes[i])))
                    if data.HasSharkFromDeep then
                        FishEat(data,FindFirstEnemy(heroes[i],250))
                    end
                end
                if times<=0 then
                    DestroyTimer(GetExpiredTimer())
                end
            end)
        end
    end
end