---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 25.02.2023 1:27
---
function CreateRamaSprite(path, parent, timed,scale)
    --[[local button = BlzCreateFrame('ScriptDialogButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)
    BlzFrameSetAbsPoint(button, FRAMEPOINT_CENTER, pointx, pointy)
    BlzFrameSetSize(button, 0.0435, 0.0435)

    local new_Frame = BlzCreateFrameByType('BACKDROP', "PORTRAIT", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "",0)
    BlzFrameSetAllPoints(new_Frame, button)
    BlzFrameSetTexture(new_Frame, "ReplaceableTextures\\CommandButtons\\BTNFootman.blp", 0, true)
    ]]

    local sprite = BlzCreateFrameByType("SPRITE", "justAName", parent, "WarCraftIIILogo", 0)
    BlzFrameClearAllPoints(sprite)
    BlzFrameSetPoint(sprite, FRAMEPOINT_BOTTOMLEFT, parent, FRAMEPOINT_BOTTOMLEFT, 0, 0)
    BlzFrameSetSize(sprite, 0.00001, 0.00001)
    BlzFrameSetScale(sprite, scale)
    BlzFrameSetModel(sprite, path, 0)

    TimerStart(CreateTimer(), timed, false, function()
        BlzDestroyFrame(sprite)
    end)
    --BlzFrameSetVisible(sprite,true)
    return sprite
end

--CreateRamaSprite("hearts_sprite",fh)